nelmio_api_doc:
    documentation:
        info:
            title: Grade API
            description: Api to deal with student's grades
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(.json)?$) # Accepts routes under /api except /api/doc
