version: '3'
services:
  grade-api:
    image: jeremiegrenier/grade-api:dev-latest
    ports:
      - 81:80
    volumes:
      - .:/var/www
  database:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432"
    env_file:
      - database.env
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
volumes:
  data:
